(() => {
"use strict";
const SHOE_DIM=128,ROAD_DIM=128,DIM=256;
const STORAGE_KEY="bgs256d_side_aware_column_v14_user_panel_v1";
const LEGACY_KEYS=["bgs256d_column_geometry_v13_user_panel_v1","bgs256d_stability_v12_user_panel_v1","bgs256d_128plus128_frozen_direct_tech_panel_v1","bgs128d_64plus64_frozen_direct_tech_panel_v1","bgs64d_32plus32_frozen_direct_tech_panel_v2","bgs32d_frozen_direct_tech_panel_v1"];
const TOTAL_CARDS=416,AVG_CARDS_PER_HAND=4.9;
const el=id=>document.getElementById(id);
const clip=(v,lo=0,hi=1)=>Math.max(lo,Math.min(hi,Number.isFinite(+v)?+v:lo));
const bp=s=>s.filter(x=>x==="B"||x==="P");
let state={history:[],active:false,lastPrediction:null};
function runs(seq){const a=bp(seq);if(!a.length)return[];const out=[];let side=a[0],n=1;for(let i=1;i<a.length;i++){if(a[i]===side)n++;else{out.push([side,n]);side=a[i];n=1}}out.push([side,n]);return out}
function bankerRatio(seq,w){const a=bp(seq).slice(-Math.max(1,w));return a.length?a.filter(x=>x==="B").length/a.length:.5}
function turnRate(seq,w){const a=bp(seq).slice(-Math.max(2,w));if(a.length<2)return .5;let t=0;for(let i=1;i<a.length;i++)if(a[i]!==a[i-1])t++;return t/(a.length-1)}
function tieRatio(seq,w=0){const a=w?seq.slice(-w):seq;return a.length?a.filter(x=>x==="T").length/a.length:0}
function binaryEntropy(seq,w=12){const a=bp(seq).slice(-w);if(!a.length)return 1;const p=a.filter(x=>x==="B").length/a.length,q=1-p;let e=0;if(p)e-=p*Math.log2(p);if(q)e-=q*Math.log2(q);return clip(e)}
function outcomeEntropy(seq,w=12){const a=seq.slice(-w);if(!a.length)return 1;let e=0;for(const o of["B","P","T"]){const p=a.filter(x=>x===o).length/a.length;if(p)e-=p*Math.log2(p)}return clip(e/Math.log2(3))}
const balance=(seq,w)=>clip(1-Math.abs(bankerRatio(seq,w)-.5)*2);
function sameTail(seq,w){const a=bp(seq).slice(-w);return a.length<w?.5:+a.every(x=>x===a[0])}
function alternatingTail(seq,w){const a=bp(seq).slice(-w);if(a.length<w)return .5;for(let i=1;i<a.length;i++)if(a[i]===a[i-1])return 0;return 1}
function runVolatility(seq,w=6){const h=runs(seq).slice(-w).map(x=>x[1]);if(h.length<2)return .25;let d=0;for(let i=1;i<h.length;i++)d+=Math.abs(h[i]-h[i-1]);return clip(d/(h.length-1)/3)}
function runTrend(seq,w=5){const h=runs(seq).slice(-w).map(x=>x[1]);return h.length<2?.5:clip(.5+((h.at(-1)-h[0])/(h.length-1))/6)}
function runStats(seq,w){const h=runs(seq).slice(-w).map(x=>x[1]);if(!h.length)return{avg:0,max:0,std:0};const m=h.reduce((a,b)=>a+b,0)/h.length,v=h.reduce((s,x)=>s+(x-m)**2,0)/h.length;return{avg:clip(m/8),max:clip(Math.max(...h)/12),std:clip(Math.sqrt(v)/6)}}
function hazard(seq){const rs=runs(seq);if(!rs.length)return .5;const current=rs.at(-1)[1],done=rs.slice(0,-1).map(x=>x[1]);if(!done.length)return clip(.38+current*.045,.35,.68);let reached=0,turned=0;for(const n of done){if(n>=current){reached++;if(n===current)turned++}}const empirical=(turned+2.5)/(reached+5),avg=done.reduce((a,b)=>a+b,0)/done.length,shape=clip(.5+(current-avg)/8,.25,.75);return clip(.72*empirical+.28*shape,.18,.82)}
function hsmmStable(seq){const tr=turnRate(seq,10),rs=runs(seq),cur=rs.length?rs.at(-1)[1]:0,r=clip(cur/6),ent=binaryEntropy(seq,12),vol=runVolatility(seq,6);const trend=Math.exp(-((((tr-.24)/.25)**2)+(((r-.66)/.34)**2)+(((vol-.24)/.28)**2))),jump=Math.exp(-((((tr-.84)/.20)**2)+(((r-.18)/.24)**2)+(((vol-.30)/.30)**2))),noise=Math.exp(-((((tr-.53)/.22)**2)+(((ent-.98)/.18)**2)+(((vol-.62)/.28)**2)));return clip((trend+jump)/(trend+jump+noise+.35))}
function derivedMark(h,c,row,newCol,off){if(newCol){if(c<off+1)return"";return h[c-1]===h[c-1-off]?"R":"U"}if(c<off)return"";const ref=h[c-off];return(ref>=row)===(ref>=row-1)?"R":"U"}
function buildDerivedRoads(seq){const a=bp(seq),sides=[],h=[],out={big_eye:[],small_road:[],cockroach_road:[]},offs={big_eye:1,small_road:2,cockroach_road:3};for(const side of a){const nc=!sides.length||side!==sides.at(-1);if(nc){sides.push(side);h.push(1)}else h[h.length-1]++;const c=h.length-1,row=h[c];for(const[k,o]of Object.entries(offs)){const m=derivedMark(h,c,row,nc,o);if(m)out[k].push(m)}}return out}
function regularity(v,w=8){const a=v.slice(-w).filter(x=>x==="R"||x==="U");return a.length?[a.filter(x=>x==="R").length/a.length,a.length]:[.5,0]}
function derivedInfo(seq,w=8){const roads=buildDerivedRoads(seq),[be,bn]=regularity(roads.big_eye,w),[sm,sn]=regularity(roads.small_road,w),[cr,cn]=regularity(roads.cockroach_road,w),m=(be+sm+cr)/3;return{be,sm,cr,bn,sn,cn,consensus:clip(1-(Math.abs(be-m)+Math.abs(sm-m)+Math.abs(cr-m))/1.5),support:clip((bn+sn+cn)/(w*3)),roads}}
function median(a){if(!a.length)return 0;const b=[...a].sort((x,y)=>x-y),m=Math.floor(b.length/2);return b.length%2?b[m]:(b[m-1]+b[m])/2}
function modeValue(a){if(!a.length)return{value:0,support:0};const counts={};for(const x of a)counts[x]=(counts[x]||0)+1;let best=a[0],count=0;for(const[k,v]of Object.entries(counts)){const n=+k;if(v>count||(v===count&&Math.abs(n-median(a))<Math.abs(best-median(a)))){best=n;count=v}}return{value:best,support:count/a.length}}
function sideColumnStats(completed,side){const values=completed.filter(x=>x[0]===side).map(x=>x[1]).slice(-8);if(!values.length)return{side,count:0,values:[],mean:0,median:0,mode:0,recent:0,std:0,slope:0,modeSupport:0,reliability:0,target:0};const mean=values.reduce((a,b)=>a+b,0)/values.length,med=median(values),mv=modeValue(values),recentVals=values.slice(-3),recent=recentVals.reduce((a,b)=>a+b,0)/recentVals.length,variance=values.reduce((s,x)=>s+(x-mean)**2,0)/values.length,std=Math.sqrt(variance),slope=values.length>=2?(values.at(-1)-values[0])/(values.length-1):0,reliability=clip(values.length/4)*clip(.45+.55*mv.support)*clip(1-std/6),target=.45*mv.value+.30*med+.25*recent;return{side,count:values.length,values,mean,median:med,mode:mv.value,recent,std,slope,modeSupport:mv.support,reliability,target}}
function pairColumnStats(completed,side){const opposite=side==="B"?"P":"B",pairs=[];for(let i=0;i<completed.length-1;i++)if(completed[i][0]===side&&completed[i+1][0]===opposite)pairs.push([completed[i][1],completed[i+1][1]]);const use=pairs.slice(-6);if(!use.length)return{count:0,leftTarget:0,rightTarget:0,leftStd:0,rightStd:0,reliability:0,pairs:[]};const left=sideColumnStats(use.map(x=>[side,x[0]]),side),right=sideColumnStats(use.map(x=>[opposite,x[1]]),opposite),reliability=clip(use.length/4)*(.5*left.reliability+.5*right.reliability);return{count:use.length,leftTarget:left.target,rightTarget:right.target,leftStd:left.std,rightStd:right.std,reliability,pairs:use}}
function candidateDerivedQuality(seq,candidate){const d=derivedInfo([...seq,candidate],8);return clip(.60*d.consensus+.40*d.support)}
function closeness(a,b){if(!b)return .5;return clip(1-Math.abs(a-b)/Math.max(3,b+1))}
function sideAwareColumnComparison(seq){const rs=runs(seq),current=rs.at(-1)||["",0];if(!current[0])return{directional:0,reliability:0,continueScore:.5,reverseScore:.5,continueSide:"",reverseSide:"",currentComplete:.5,continuationNeed:.5,pairReversal:0,own:{},opposite:{},pair:{}};const completed=rs.slice(0,-1),currentSide=current[0],reverseSide=currentSide==="B"?"P":"B",own=sideColumnStats(completed,currentSide),opposite=sideColumnStats(completed,reverseSide),pair=pairColumnStats(completed,currentSide),cur=current[1],target=own.target||cur,nextHeight=cur+1,continueFit=closeness(nextHeight,target),continuationNeed=own.count?clip((target-cur+.35)/Math.max(1.5,target)):.35,currentComplete=own.count?closeness(cur,target):.5,overComplete=own.count?clip((cur-target)/Math.max(2,target)):0,pairLeftFit=pair.count?closeness(cur,pair.leftTarget):.5,pairReversal=pairLeftFit*pair.reliability,continueDerived=candidateDerivedQuality(seq,currentSide),reverseDerived=candidateDerivedQuality(seq,reverseSide),continueBase=.48*continueFit+.28*continuationNeed+.16*own.reliability+.08*(1-overComplete),reverseBase=.38*currentComplete+.28*pairLeftFit+.18*pair.reliability+.12*opposite.reliability+.04*overComplete,continueScore=clip(.90*continueBase+.10*continueDerived),reverseScore=clip(.90*reverseBase+.10*reverseDerived),gap=continueScore-reverseScore,support=clip(.42*own.reliability+.20*opposite.reliability+.28*Math.max(pair.reliability,own.reliability)+.10*Math.max(continueDerived,reverseDerived)),reliability=clip(support*(.55+.45*Math.min(1,Math.abs(gap)*3))),directional=(currentSide==="B"?1:-1)*clip(gap/.35,-1,1),reverseEvidence=clip(.34*currentComplete+.26*pairLeftFit+.20*pair.reliability+.14*opposite.reliability+.06*overComplete),continueEvidence=clip(.52*continueFit+.32*continuationNeed+.16*own.reliability);return{directional:clip(directional,-1,1),reliability,continueScore,reverseScore,continueSide:currentSide,reverseSide,currentComplete,continuationNeed,pairReversal,reverseEvidence,continueEvidence,own,opposite,pair,continueDerived,reverseDerived}}
function buildShoeVector(seq){const used=Math.min(TOTAL_CARDS,seq.length*AVG_CARDS_PER_HAND),remaining=Math.max(0,TOTAL_CARDS-used),rr=clip(remaining/TOTAL_CARDS),pen=clip(1-rr),maturity=clip(seq.length/70),hands=clip(seq.length/(TOTAL_CARDS/AVG_CARDS_PER_HAND)),v=[rr,pen,maturity,hands,tieRatio(seq),balance(seq,Math.max(1,bp(seq).length)),binaryEntropy(seq,12),outcomeEntropy(seq,12),clip(1-Math.abs(pen-.125)/.125),clip(1-Math.abs(pen-.375)/.125),clip(1-Math.abs(pen-.625)/.125),clip(1-Math.abs(pen-.875)/.125),clip(seq.length/8),clip(seq.length/16),clip(seq.length/32),clip(seq.length/64)];for(const w of[2,4,6,8,12,16,24,32,48,64])v.push(tieRatio(seq,w),binaryEntropy(seq,w),outcomeEntropy(seq,w),balance(seq,w));for(const w of[3,5,7,10,14,20,28,40,56])v.push(tieRatio(seq,w),binaryEntropy(seq,w),outcomeEntropy(seq,w),balance(seq,w));v.push(pen**2,pen**3,Math.sqrt(pen),Math.sqrt(Math.sqrt(pen)),rr**2,rr**3,Math.sqrt(rr),Math.sqrt(Math.sqrt(rr)),maturity**2,Math.sqrt(maturity),clip(Math.log1p(seq.length)/Math.log1p(128)),1);v.push(clip(.5+(tieRatio(seq,4)-tieRatio(seq,16))/2),clip(.5+(tieRatio(seq,8)-tieRatio(seq,32))/2),clip(.5+(tieRatio(seq,16)-tieRatio(seq,64))/2),clip(.5+(binaryEntropy(seq,4)-binaryEntropy(seq,16))/2),clip(.5+(binaryEntropy(seq,8)-binaryEntropy(seq,32))/2),clip(.5+(binaryEntropy(seq,16)-binaryEntropy(seq,64))/2),clip(.5+(outcomeEntropy(seq,4)-outcomeEntropy(seq,16))/2),clip(.5+(outcomeEntropy(seq,8)-outcomeEntropy(seq,32))/2),clip(.5+(outcomeEntropy(seq,16)-outcomeEntropy(seq,64))/2),clip(.5+(balance(seq,4)-balance(seq,16))/2),clip(.5+(balance(seq,8)-balance(seq,32))/2),clip(.5+(balance(seq,16)-balance(seq,64))/2));v.push(clip(1-pen/.30),clip(1-Math.abs(pen-.45)/.30),clip((pen-.55)/.35),clip(1-pen/.16),clip(1-Math.abs(pen-.30)/.20),clip(1-Math.abs(pen-.62)/.24),clip((pen-.76)/.20),clip(seq.length/4),clip(seq.length/12),clip(seq.length/20),clip(seq.length/28),clip(seq.length/40));if(v.length!==SHOE_DIM)throw new Error(`shoe vector mismatch: ${v.length}`);return v}
function buildRoadVector(seq){const rs=runs(seq),current=rs.at(-1)||["",0],prior=i=>rs.length>i?rs.at(-1-i):["",0],d8=derivedInfo(seq,8),hz=hazard(seq),hs=hsmmStable(seq),s4=runStats(seq,4),s6=runStats(seq,6),s8=runStats(seq,8),s12=runStats(seq,12),side=sideAwareColumnComparison(seq),runDelta=rs.length>1?clip(.5+(current[1]-prior(1)[1])/12):.5,v=[current[0]==="B"?1:current[0]==="P"?0:.5,current[0]==="P"?1:current[0]==="B"?0:.5,clip(current[1]/8),...[1,2,3,4,5,6].map(i=>clip(prior(i)[1]/8)),hz,clip(1-hz),hs,runVolatility(seq,6),runTrend(seq,5),d8.be,d8.sm,d8.cr,d8.consensus,d8.support,clip((d8.be+d8.sm+d8.cr)/3),sameTail(seq,2),sameTail(seq,3),alternatingTail(seq,4),alternatingTail(seq,6)];for(const w of[2,4,6,8,10,12,16,20,24,32,48,64])v.push(bankerRatio(seq,w));for(const w of[2,4,6,8,10,12,16,20,24,32,48,64])v.push(turnRate(seq,w));for(const w of[4,6,8,12,16,24,32]){const d=derivedInfo(seq,w);v.push(d.be,d.sm,d.cr)}v.push(s4.avg,s6.avg,s8.avg,s12.avg,s4.max,s8.max,s12.max,s4.std,s8.std,s12.std,runTrend(seq,8),runTrend(seq,12),runDelta);v.push(alternatingTail(seq,3),alternatingTail(seq,5),alternatingTail(seq,8),alternatingTail(seq,10),sameTail(seq,4),sameTail(seq,5),sameTail(seq,6),sameTail(seq,7),sameTail(seq,8),sameTail(seq,10));v.push(clip(.5+(bankerRatio(seq,4)-bankerRatio(seq,16))/2),clip(.5+(bankerRatio(seq,8)-bankerRatio(seq,32))/2),clip(.5+(bankerRatio(seq,16)-bankerRatio(seq,64))/2),clip(.5+(turnRate(seq,4)-turnRate(seq,16))/2),clip(.5+(turnRate(seq,8)-turnRate(seq,32))/2),clip(.5+(turnRate(seq,16)-turnRate(seq,64))/2));v.push(hz**2,(1-hz)**2,hs**2,d8.consensus**2);const own=side.own||{},opp=side.opposite||{},pair=side.pair||{};v.push(clip((own.target||0)/8),clip((own.mean||0)/8),clip((own.median||0)/8),clip((own.mode||0)/8),clip((own.recent||0)/8),clip((own.std||0)/6),clip(.5+(own.slope||0)/6),clip(own.reliability||0),clip((opp.target||0)/8),clip((opp.mean||0)/8),clip((opp.median||0)/8),clip((opp.mode||0)/8),clip((opp.recent||0)/8),clip((opp.std||0)/6),clip(.5+(opp.slope||0)/6),clip(opp.reliability||0),clip(current[1]/8),clip(side.currentComplete||0),clip(side.continuationNeed||0),clip((pair.leftTarget||0)/8),clip((pair.rightTarget||0)/8),clip(pair.reliability||0),clip(side.continueScore||.5),clip(side.reverseScore||.5),clip(.5+side.directional/2),clip(side.reliability||0));if(v.length!==ROAD_DIM)throw new Error(`road vector mismatch: ${v.length}`);return v}
function context256(seq){const shoe=buildShoeVector(seq),road=buildRoadVector(seq),vector=[...shoe,...road];if(vector.length!==DIM)throw new Error(`context mismatch: ${vector.length}`);return vector}
function pairPattern(seq){const rs=runs(seq);if(rs.length<4)return{reliability:0,direction:0};const completed=rs.slice(0,-1).slice(-5).map(x=>x[1]),support=completed.filter(x=>x===2).length/Math.max(1,completed.length),current=rs.at(-1),side=current[0]==="B"?1:-1;return{reliability:clip((support-.35)/.55),direction:current[1]<=1?side:-side}}
function deterministicDirection(seq){let hash=0;const token="BGS256_SIDE_V14|"+seq.join("");for(let i=0;i<token.length;i++)hash=(hash*31+token.charCodeAt(i))>>>0;return hash%2?"B":"P"}
function analyzeStable(seq){const values=bp(seq),rs=runs(seq),current=rs.at(-1)||["",0],sign=current[0]==="B"?1:current[0]==="P"?-1:0,r4=bankerRatio(seq,4),r8=bankerRatio(seq,8),r16=bankerRatio(seq,16),r24=bankerRatio(seq,24),r32=bankerRatio(seq,32),r64=bankerRatio(seq,64),t4=turnRate(seq,4),t8=turnRate(seq,8),t16=turnRate(seq,16),hz=hazard(seq),hs=hsmmStable(seq),vol=runVolatility(seq,6),derived=derivedInfo(seq,8),pair=pairPattern(seq),column=sideAwareColumnComparison(seq),shortBias=.45*((r4-.5)*2)+.55*((r8-.5)*2),midBias=.55*((r16-.5)*2)+.45*((r24-.5)*2),longBias=.55*((r32-.5)*2)+.45*((r64-.5)*2),ratioDirectional=.44*shortBias+.34*midBias+.22*longBias,ratioDivergence=.60*(shortBias-midBias)+.40*(midBias-longBias),trendRel=clip(.20+.34*(1-t8)+.20*(1-hz)+.16*hs+.10*Math.max(0,sameTail(seq,3)-.5)*2),altRel=clip(.08+.58*clip((t8-.52)/.40)+.18*alternatingTail(seq,4)+.10*alternatingTail(seq,6)-.20*Math.max(0,sameTail(seq,3)-.5)*2),genericReversalRel=clip(.08+.25*hz+.18*Math.abs(t4-t16)+.12*vol+.10*(1-hs)),reversalRel=clip(.55*genericReversalRel+.45*column.reverseEvidence),trendComponent=sign*clip(.50*(1-t8)+.28*(1-hz)+.22*hs),alternateComponent=-sign*clip((t8-.50)/.42),reversalComponent=clip(-sign*clip((hz-.46)/.36)*.45+ratioDivergence*.45+column.directional*.55,-1,1),maturity=clip(values.length/24),conflict=clip(Math.abs(t4-t16)*.55+Math.abs(shortBias-longBias)*.45+vol*.35+Math.abs(column.continueScore-column.reverseScore)*.15),structureConfidence=clip(.20+.18*hs+.14*derived.consensus+.10*derived.support+.14*maturity+.24*column.reliability-.18*conflict);let score=.14*ratioDirectional+.14*trendRel*trendComponent+.08*altRel*alternateComponent+.08*reversalRel*reversalComponent+.06*pair.reliability*pair.direction+.50*column.reliability*column.directional;score*=.60+.40*structureConfidence;score=clip(score,-1,1);const candidates=[["柱型",column.reliability],["趨勢",trendRel],["跳動",altRel],["轉折",reversalRel],["雙跳",pair.reliability]].sort((a,b)=>b[1]-a[1]);let regime="混合";if(candidates[0][1]-candidates[1][1]>=.08&&candidates[0][1]>=.48)regime=candidates[0][0];let direction,reason;if(Math.abs(score)<.03){if(column.reliability>=.35&&Math.abs(column.directional)>=.35){direction=column.directional>0?"B":"P";reason="低總差距由莊閒柱高模板判定"}else{direction=deterministicDirection(seq);reason="低差距固定歷史判定"}}else{direction=score>0?"B":"P";reason="莊閒分離柱高＋反轉候選評分"}const confidence=clip(.50+Math.min(.09,Math.abs(score)*.11+Math.max(0,structureConfidence-.5)*.03),.50,.59);return{direction,confidence,score,reason,regime,structureConfidence,context:context256(seq),diagnostics:{shortBias,midBias,longBias,ratioDivergence,trendRel,altRel,reversalRel,hazard:hz,hsmm:hs,derivedConsensus:derived.consensus,column}}}
function save(){try{localStorage.setItem(STORAGE_KEY,JSON.stringify(state))}catch(_){}}
function load(){try{const own=localStorage.getItem(STORAGE_KEY);if(own){const raw=JSON.parse(own);if(raw&&Array.isArray(raw.history)){state.history=raw.history.filter(x=>["B","P","T"].includes(x)).slice(-500);return}}for(const key of LEGACY_KEYS){const text=localStorage.getItem(key);if(!text)continue;const raw=JSON.parse(text);if(raw&&Array.isArray(raw.history)){state.history=raw.history.filter(x=>["B","P","T"].includes(x)).slice(-500);save();return}}}catch(_){}}
function clearAllStorage(){try{localStorage.removeItem(STORAGE_KEY);for(const key of LEGACY_KEYS)localStorage.removeItem(key)}catch(_){}}
function setMessage(text,warning=false){const box=el("message");if(!box)return;box.textContent=text;box.classList.toggle("warning",warning)}
function addOutcome(outcome){if(!["B","P","T"].includes(outcome))return;state.history.push(outcome);state.active=false;state.lastPrediction=null;save();setMessage(`已記錄第 ${state.history.length} 局`);render()}
function startAnalysis(){if(!state.history.length){setMessage("請先輸入牌局紀錄",true);return}state.lastPrediction=analyzeStable(state.history);state.active=true;save();setMessage(`第 ${state.history.length+1} 局分析完成`);render()}
function backOne(){if(!state.history.length){setMessage("目前沒有可返回的紀錄",true);return}state.history.pop();state.active=false;state.lastPrediction=null;save();setMessage("已返回上一局");render()}
function endAnalysis(){state={history:[],active:false,lastPrediction:null};clearAllStorage();setMessage("本靴資料已清空");render()}
function renderHistory(){const box=el("historyTrack");if(!state.history.length){box.innerHTML='<div class="empty-history">尚未輸入牌局</div>';return}box.innerHTML=state.history.map((v,i)=>`<span class="history-chip ${v}" title="第 ${i+1} 局">${v}</span>`).join("");box.scrollLeft=box.scrollWidth}
function renderPrediction(){const p=state.active?state.lastPrediction:null,orb=el("directionOrb");if(!p){el("directionText").textContent="—";el("directionCode").textContent="等待分析";el("confidence").textContent="—";el("regime").textContent="—";el("strength").textContent="—";orb.className="direction-orb idle";return}const isB=p.direction==="B";el("directionText").textContent=isB?"莊":"閒";el("directionCode").textContent=isB?"BANKER":"PLAYER";el("confidence").textContent=(p.confidence*100).toFixed(1)+"%";el("regime").textContent=p.regime;el("strength").textContent=p.structureConfidence>=.68?"穩定":p.structureConfidence>=.52?"中等":"保守";orb.className="direction-orb "+(isB?"banker":"player")}
function render(){el("roundPill").textContent=`${state.history.length} 局`;el("modePill").textContent=state.active?"分析完成":"準備中";el("roundCount").textContent=state.history.length;renderPrediction();renderHistory()}
el("btnB").addEventListener("click",()=>addOutcome("B"));el("btnP").addEventListener("click",()=>addOutcome("P"));el("btnT").addEventListener("click",()=>addOutcome("T"));el("btnStart").addEventListener("click",startAnalysis);el("btnBack").addEventListener("click",backOne);el("btnEnd").addEventListener("click",endAnalysis);load();render();
})();